const express= require('express');
const router=express.Router();
const passport=require('passport');
console.log("router loaded sucessfully");
const homeController=require('../controllers/home_controllers');
router.get('/',homeController.home);
router.get('/profile',passport.checkAuthentication,homeController.profile);
router.get('/profile/rent',passport.checkAuthentication,homeController.rent_products);
router.get('/profile/purchased',passport.checkAuthentication,homeController.purchased_products);
router.get('/profile/hire',passport.checkAuthentication,homeController.hire_products);
router.get('/return/:id',passport.checkAuthentication,homeController.return_product);
router.post('/profile/edit',passport.checkAuthentication,homeController.edit);
router.get('/order/:id',passport.checkAuthentication,homeController.order);
router.post('/order/:price',passport.checkAuthentication,homeController.pay);
router.post('/is-order-complete/:id',passport.checkAuthentication,homeController.complete_payment);
router.use('/users',require('./user.js'));
router.use('/products',require('./product.js'));
module.exports=router;