const express= require('express');
const router=express.Router();
console.log("router loaded sucessfully");
const homeController=require('../controllers/home_controllers');
router.get('/',homeController.home);
router.get('/profile',homeController.profile);
router.get('/profile/rent',homeController.rent_products);
router.get('/profile/purchased',homeController.purchased_products);
router.get('/profile/hire',homeController.hire_products);
router.get('/return/:id',homeController.return_product);
router.post('/profile/edit',homeController.edit);
router.get('/order/:id',homeController.order);
router.post('/order/:price',homeController.pay);
router.post('/is-order-complete/:id',homeController.complete_payment);
router.use('/users',require('./user.js'));
router.use('/products',require('./product.js'));
module.exports=router;
