const express= require('express');
const router=express.Router();
console.log("router loaded sucessfully");
const homeController=require('../controllers/home_controllers');
router.get('/',homeController.home);
router.get('/order',homeController.order);
router.post('/order',homeController.pay);
router.post('/is-order-complete',homeController.complete_payment);
router.use('/users',require('./user.js'));
router.use('/products',require('./product.js'));
module.exports=router;
